DROP DATABASE IF EXISTS MassBank;
CREATE DATABASE MassBank;
USE MassBank;

--
-- Table structure for table `PEAK`
--
DROP TABLE IF EXISTS PEAK;
CREATE TABLE PEAK (
	ID        CHAR(16)  NOT NULL,
	MZ        DOUBLE   NOT NULL,
	INTENSITY FLOAT    NOT NULL,
	RELATIVE  SMALLINT NOT NULL,
	UNIQUE(ID,MZ)
)ENGINE=InnoDB;

--
-- Table structure for table `RECORD`
--
DROP TABLE IF EXISTS RECORD;
CREATE TABLE RECORD (
	ID             CHAR(16)          NOT NULL,
	COMPOUND_NO    SMALLINT UNSIGNED NOT NULL,
	INSTRUMENT_NO  TINYINT  UNSIGNED NOT NULL,
	MS_TYPE        VARCHAR(8)        NOT NULL,
	TITLE_ADDITION VARCHAR(255),
	ION            TINYINT           NOT NULL,
	PRECURSOR_MZ   SMALLINT   UNSIGNED,
	FULL_TEXT      TEXT              NOT NULL,
	PRIMARY KEY(ID),
	INDEX(COMPOUND_NO)
)ENGINE=InnoDB;

--
-- Table structure for table `CHEMICAL_STRUCTURE_DATA`
--
DROP TABLE IF EXISTS COMPOUND_INFO;
CREATE TABLE COMPOUND_INFO (
	COMPOUND_NO    SMALLINT UNSIGNED    NOT NULL,
	COMPOUND_NAME  VARCHAR(255) binary NOT NULL,
	FORMULA        VARCHAR(30),
	EXACT_MASS     DOUBLE,
	SMILES         TEXT,
	INCHI          TEXT,
	MOLFILE        TEXT,
	PRIMARY KEY(COMPOUND_NO)
)ENGINE=InnoDB;

--
-- Table structure for table `COMPOUND_NAMES`
--
DROP TABLE IF EXISTS COMPOUND_NAMES;
CREATE TABLE COMPOUND_NAMES (
	ID             CHAR(16)             NOT NULL,
	COMPOUND_NAME  VARCHAR(255) binary  NOT NULL,
	PRIMARY KEY(ID,COMPOUND_NAME)
)ENGINE=InnoDB;

--
-- Table structure for table `INSTRUMENT`
--
DROP TABLE IF EXISTS INSTRUMENT;
CREATE TABLE INSTRUMENT (
	INSTRUMENT_NO   TINYINT UNSIGNED   NOT NULL,
	INSTRUMENT_TYPE VARCHAR(50)        NOT NULL,
	INSTRUMENT_NAME VARCHAR(255)       NOT NULL,
	PRIMARY KEY(INSTRUMENT_NO)
)ENGINE=InnoDB;

GRANT ALL PRIVILEGES ON *.* TO massbank@localhost IDENTIFIED BY 'massbank2014' WITH GRANT OPTION;
